### ISSUE TITLE
Potential outreach partners

### ISSUE THREAD

**Issue by gabbyjones** [codeforamerica/health#68]
**Housing**
- [x] Tenderloin Housing Clinic https://github.com/codeforamerica/health/issues/43
- [ ] San Francisco Public Housing Authority
- [ ] San Mateo Housing Authority
- [ ] Housing Leadership Council of San Mateo County
- [ ] HIP Housing
- [ ] SMC Housing
- [ ] West Bay Housing
- [ ] Mid-Peninsula Housing Coalition
- [ ] BRIDGE Housing Corporation

**CBO's**
- [x] Golden Gate Regional Center https://github.com/codeforamerica/health/issues/65
- [x] Homeless Prenatal Program - issue needed @alanjosephwilliams 

**Re-entry organizations**

**HSA's**
- [x] San Francisco County
- [x] Contra Costa County 
- [x] Solano County
- [ ] San Mateo
- [ ] Alameda
- [ ] San Diego
- [ ] Los Angeles

**WIC Enrollment Sites**

**Food Banks**
- [x] Humboldt County Food Bank https://github.com/codeforamerica/health/issues/69

**School Districts**
- [ ] San Mateo County School District
  - [ ] Jefferson Union High School District
  - [ ] San Mateo Union High School District
  - [ ] Sequoia Union High School District
- [ ] San Francisco County School District

**Americorps**
- [ ] See https://sfccc.squarespace.com for sites/contacts in SF

**Comment by lippytak** [comment]
Added Americorps to the list above because (1) all (most?) of them enroll in Food Stamps as part of program enrollment and (2) they probably work in communities with high participation rates. I think we could learn a lot from them.
